language: rust
rust:
- stable
- nightly
matrix:
  allow_failures:
  - rust: nightly
env:
  global:
  - secure: Im9ZHCwz6xIPJWjFPNCjcdF86htdWd6RXwFR3NNo8mn0ZkLP93kb2Pt0H9os5YyBueRpgYgQ0xq4osfTjiRssS+09RC5FSW2AnL/EQ7y0SBeeKiPxi31P4C6frCYZW9DURva2dFYAWURRguKeLwuob13xkGNSpjrfFuNYHsQcq59777rOB81/sfDQPfR7JKYJBwrS1XonY0Xd+CTe4EeDc4OzGNZtHcswgx4fWjGW9hmIT926TBoCr6IJK9KA9Zfu7xU0mgUiW7d7BJqxxlNEtaO3eGVJj/+9eI0ai6KOEs/tNfHE5qEFCe2dNc1ClE1Hd9dXVslK6LiaUBh/fv9KxyE9DUAbQU48XgmnpIy0JQqfttaEIQlsiXe2r7PJ6Ad0OMWZvKqGX967bMXqG6kZajsIxFG74lxA13RbkTfDFOXIhhKif8yLoGxiRCLmsPKY1FMoRKVBSOs2rbg/XV5FYSo1FwomJQt+YHzanknN8Rgx9sE9MITARdSoeDkIqoi7JJlHxe/uSBSf1IR+yMKVUo4642oBptttQTZNjcTXuinqrTlfuMZYKXzM774C5TetUVKAXRcNKP5kdlIjcAD6JKymZSYu+ZqZy2Tl7EN3YtuSx0NXshgdQquRHqFu7Ovx8onghhIv1NZ4guM7NXdtSm8VVpUhQ/LkybdW9jx/I0=
script:
- cargo test --verbose
after_success:
- |
  [ $TRAVIS_RUST_VERSION = stable ] &&
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo publish --token ${CRATESIO_TOKEN}
