language: rust

rust:
- stable
- nightly
matrix:
  allow_failures:
  - rust: nightly
env:
  global:
script:
- cargo test --verbose
# after_success:
# - |
#   [ $TRAVIS_RUST_VERSION = stable ] &&
#   [ $TRAVIS_BRANCH = master ] &&
#   [ $TRAVIS_PULL_REQUEST = false ] &&
#   cargo doc &&
#   sudo pip install ghp-import &&
#   ghp-import -n target/doc &&
#   git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
# - |
#   [ $TRAVIS_RUST_VERSION = stable ] &&
#   [ $TRAVIS_BRANCH = master ] &&
#   [ $TRAVIS_PULL_REQUEST = false ] &&
#   cargo publish --token ${CRATESIO_TOKEN}
